baseURL = "https://www.glazemixup.com/"
title = "Mixup"

# theme = "bento"
author = "Ken Chin-Purcell"
copyright = "MIT"

[params]
  # Show intro in the home page (with headline and description)
  intro = true
  headline = "Mixup is a galze chemistry calculator"
  description = "Glaze calculation for the timid"

# Items in the top menu
[menu]
  [[menu.main]]
      name = "Mixup"
      url = "/"
      weight = 1

  [[menu.main]]
      name = "Features"
      url = "/features"
      weight = 2

  [[menu.main]]
      name = "Documentation"
      url = "/docs"
      weight = 3

  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 4
